WebUoFASM1/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace WebUoFASM1.Models
{
    public class Category
    {
        public int Id { get; set; }

        [Required]
        [DisplayName("Category Name")]
        [Remote("IsProductNameExist", "Category", AdditionalFields = "Id",
                ErrorMessage = "Product name already exists")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Category Description")]
        public string Description { get; set; }
    }
}

WebUoFASM1/Controllers/CategoriesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebUoFASM1.Models;

namespace WebUoFASM1.Controllers
{
    [Authorize(Roles = "Staff")]
    public class CategoriesController : Controller

    {
        private ApplicationDbContext _context;

        public CategoriesController()
        {
            _context = new ApplicationDbContext();
        }

        public ActionResult Index()
        {
            var list = _context.Categories.ToList();
            return View(list);
        }

        [Authorize(Roles = "Staff")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            bool IsProductNameExist = _context.Categories.Any
                 (x => x.Name == category.Name && x.Id != category.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Category Name already exists");
            }

            if (ModelState.IsValid)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        public JsonResult IsProductNameExist(string ProductName, int? Id)
        {
            var validateName = _context.Categories.FirstOrDefault
                                (x => x.Name == ProductName && x.Id != Id);
            if (validateName != null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Staff")]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Category category = _context.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name, Description")]
                          Category category)
        {
            bool IsProductNameExist = _context.Categories.Any
                            (x => x.Name == category.Name && x.Id != category.Id);
            if (IsProductNameExist == true)
            {
                ModelState.AddModelError("Name", "Category Name already exists");
            }

            if (ModelState.IsValid)
            {
                _context.Entry(category).State = EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        [Authorize(Roles = "Staff")]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var productInDb = _context.Categories.SingleOrDefault(p => p.Id == id);

            if (productInDb == null)
            {
                return HttpNotFound();
            }

            _context.Categories.Remove(productInDb);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebUoFASM1/Views/Categories/Create.cshtml
@model WebUoFASM1.Models.Category
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Categories", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.LabelFor(p => p.Name)
    @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Name)
    @Html.LabelFor(p => p.Description)
    @Html.TextBoxFor(p => p.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Description)
    <input type="submit" value="Create" class="btn-primary" />
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebUoFASM1/Views/Categories/Delete.cshtml
@model WebUoFASM1.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebUoFASM1/Views/Categories/Edit.cshtml
@model WebUoFASM1.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Category</h2>

@using (Html.BeginForm("Edit", "Categories", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.LabelFor(p => p.Name)
    @Html.TextBoxFor(p => p.Name, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Name)
    @Html.LabelFor(p => p.Description)
    @Html.TextBoxFor(p => p.Description, new { @class = "form-control" })
    @Html.ValidationMessageFor(p => p.Description)
    <input type="submit" value="Edit" class="btn-primary" />
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WebUoFASM1/Views/Categories/Index.cshtml
@model IEnumerable<WebUoFASM1.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>